#ifndef CIMC_PROTOCOL_DEFS_H
#define CIMC_PROTOCOL_DEFS_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CIMC_FRAME_START             0xA5B6U
#define CIMC_FRAME_END               0xB6A5U
#define CIMC_PROTOCOL_VERSION        0x02U
#define CIMC_DEVICE_ID_BROADCAST     0xFFFFU

#define CIMC_FRAME_MIN_BINARY_LEN    13U
#define CIMC_FRAME_MAX_PAYLOAD_LEN   255U
#define CIMC_FRAME_MAX_BINARY_LEN    (CIMC_FRAME_MIN_BINARY_LEN + CIMC_FRAME_MAX_PAYLOAD_LEN)
#define CIMC_FRAME_MAX_ASCII_LEN     (CIMC_FRAME_MAX_BINARY_LEN * 2U)

typedef enum {
    CIMC_FRAME_TYPE_COMMAND = 0x01U,
    CIMC_FRAME_TYPE_RESPONSE = 0x02U,
    CIMC_FRAME_TYPE_HEARTBEAT = 0x05U,
    CIMC_FRAME_TYPE_ERROR = 0xFFU
} cimc_frame_type_t;

typedef enum {
    CIMC_CMD_REBOOT = 0x0101U,
    CIMC_CMD_QUERY_FW_VERSION = 0x0104U,
    CIMC_CMD_SET_TIME = 0x0105U,
    CIMC_CMD_QUERY_TIME = 0x0106U,
    CIMC_CMD_QUERY_DEVICE_ID = 0x0111U,
    CIMC_CMD_QUERY_BAUDRATE = 0x0112U,
    CIMC_CMD_SET_DEVICE_ID = 0x01A1U,
    CIMC_CMD_SET_BAUDRATE = 0x01A2U,

    CIMC_CMD_QUERY_CH0 = 0x0201U,
    CIMC_CMD_QUERY_CH1 = 0x0202U,
    CIMC_CMD_QUERY_PT100 = 0x0221U,
    CIMC_CMD_SET_CH0_RATIO = 0x0241U,
    CIMC_CMD_SET_CH1_RATIO = 0x0242U,
    CIMC_CMD_SET_REPORT_INTERVAL = 0x0261U,

    CIMC_CMD_SET_DAC = 0x0301U,
    CIMC_CMD_START_AUTO_REPORT = 0x0302U,
    CIMC_CMD_STOP_AUTO_REPORT = 0x0303U,
    CIMC_CMD_SLEEP = 0x03AAU,

    CIMC_CMD_READ_THRESHOLDS = 0x0400U,
    CIMC_CMD_READ_CH0_THRESHOLD = 0x0401U,
    CIMC_CMD_READ_CH1_THRESHOLD = 0x0402U,
    CIMC_CMD_READ_CH2_THRESHOLD = 0x0403U,
    CIMC_CMD_WRITE_CH0_THRESHOLD = 0x0411U,
    CIMC_CMD_WRITE_CH1_THRESHOLD = 0x0412U,
    CIMC_CMD_WRITE_CH2_THRESHOLD = 0x0413U,

    CIMC_CMD_UPGRADE_REQUEST = 0x0501U,
    CIMC_CMD_UPGRADE_PREPARE = 0x0502U,
    CIMC_CMD_UPGRADE_EXECUTE = 0x0503U,

    CIMC_CMD_ALARM_ENABLE = 0x0601U,
    CIMC_CMD_ALARM_QUERY = 0x0602U,
    CIMC_CMD_ALARM_CLEAR = 0x0603U,

    CIMC_CMD_HEARTBEAT = 0x8888U,
    CIMC_CMD_BROADCAST_DISCOVERY = 0xFFFFU,
    CIMC_CMD_ERROR_GENERIC = 0xEEEEU
} cimc_command_t;

typedef enum {
    CIMC_PARSE_OK = 0,
    CIMC_PARSE_NULL,
    CIMC_PARSE_TOO_SHORT,
    CIMC_PARSE_TOO_LONG,
    CIMC_PARSE_BAD_ASCII,
    CIMC_PARSE_BAD_MARKER,
    CIMC_PARSE_BAD_VERSION,
    CIMC_PARSE_BAD_LENGTH,
    CIMC_PARSE_BAD_CRC
} cimc_parse_result_t;

typedef struct {
    uint16_t device_id;
    uint8_t type;
    uint16_t command;
    uint8_t payload_len;
    uint8_t version;
    uint8_t payload[CIMC_FRAME_MAX_PAYLOAD_LEN];
} cimc_frame_t;

#ifdef __cplusplus
}
#endif

#endif /* CIMC_PROTOCOL_DEFS_H */
